# Use of NumPy

### 1D array

In [2]:
import numpy as np

A = np.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


### 2D array

In [5]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[8,8,9]])
print(B)
print(type(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 8 9]]
<class 'numpy.ndarray'>


### 3D array

In [9]:
C = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[4,5]],[[1,2],[3,4],[4,5]]])
print(C)
print(type(C))

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [4 5]]

 [[1 2]
  [3 4]
  [4 5]]]
<class 'numpy.ndarray'>


### printing 2nd element of 3rd row of 2nd matrix

In [10]:
print(C[1,2,1])

5


In [12]:
fruits = np.array(["apple","banana","cherry"])
print(fruits[1])

banana


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# generate random data-set
np.random.seed(0)
x = np.random.rand(100, 1) #Generate a 2-D array with 100 rows, each row containing 1
random numbers:
y = 2 + 3 * x + np.random.rand(100, 1)
regression_model = LinearRegression() # Model initialization
regression_model.fit(x, y) # Fit the data(train the model)
y_predicted = regression_model.predict(x) # Predict
# model evaluation
rmse = mean_squared_error(y, y_predicted)
r2 = r2_score(y, y_predicted)
# printing values
print(&#39;Slope:&#39; ,regression_model.coef_)
print(&#39;Intercept:&#39;, regression_model.intercept_)
print(&#39;Root mean squared error: &#39;, rmse)
print(&#39;R2 score: &#39;, r2)
# plotting values # data points
plt.scatter(x, y, s=10)
plt.xlabel(&#39;x-Values from 0-1&#39;)
plt.ylabel(&#39;y-values from 2-5&#39;)
# predicted values
plt.plot(x, y_predicted, color=&#39;r&#39;)
plt.show() )